import type { Quiz } from '@/types/course';

export const module5Quiz: Quiz = {
  id: 5,
  title: 'Module 5 Quiz: AI-Powered Backend Scaffolding',
  description: 'This quiz tests your understanding of leveraging AI to streamline backend development, including setting up Node.js, Django, and Flask environments, crafting database queries, integrating AI APIs, and building a full-stack application. It covers practical applications, best practices, and ethical considerations for creating scalable, AI-enhanced web applications. Each question includes a correct answer and explanation.',
  questions: [
    {
      id: 1,
      question: 'What is the primary purpose of using AI in backend development as described in the module?',
      options: [
        'To replace all manual server-side coding',
        'To automate setup, generate code, and optimize database queries',
        'To design frontend layouts',
        'To host applications directly'
      ],
      correctAnswer: 1,
      explanation: 'AI streamlines backend development by generating boilerplate code, configuring frameworks (e.g., Node.js, Django), and optimizing queries for SQL/NoSQL databases. It does not replace manual coding, design frontend layouts, or handle hosting.'
    },
    {
      id: 2,
      question: 'What does the following AI-generated Node.js code do?\n\nconst express = require(\'express\');\nconst app = express();\napp.use(express.json());\napp.get(\'/api/posts\', (req, res) => {\n  res.json([{ id: 1, title: \'Post 1\' }]);\n});\napp.listen(3000, () => console.log(\'Server running on port 3000\'));',
      options: [
        'Creates a form validation script',
        'Sets up an Express server with a GET endpoint for posts',
        'Designs a MongoDB schema',
        'Integrates an OpenAI chatbot'
      ],
      correctAnswer: 1,
      explanation: 'The code initializes an Express server, enables JSON parsing, and defines a GET endpoint (/api/posts) that returns a JSON array of posts. It does not handle forms, schemas, or AI APIs.'
    },
    {
      id: 3,
      question: 'Which AI tool is best suited for generating a Django model for a user profile?',
      options: [
        'Lighthouse',
        'Claude',
        'BrowserStack',
        'Postman'
      ],
      correctAnswer: 1,
      explanation: 'Claude generates Django models, views, or other Python code from prompts, ideal for backend tasks. Lighthouse audits performance, BrowserStack tests responsiveness, and Postman tests APIs, not code generation.'
    },
    {
      id: 4,
      question: 'What is an example of an AI-generated SQL query output?',
      options: [
        'db.products.find({ category: "electronics" }).toArray();',
        'SELECT u.name, u.email FROM users u JOIN orders o ON u.id = o.user_id WHERE o.total > 100;',
        'app.get(\'/api/users\', (req, res) => res.json([]));',
        'const task = new Task(req.body);'
      ],
      correctAnswer: 1,
      explanation: 'This is a SQL query to fetch user data based on order totals, generated by AI. Option A is MongoDB (NoSQL), C is Express code, and D is Mongoose, not SQL.'
    },
    {
      id: 5,
      question: 'What is a key feature of integrating the OpenAI API into a backend application?',
      options: [
        'Generating static HTML pages',
        'Adding natural language processing like chatbots',
        'Creating database schemas automatically',
        'Styling frontend components'
      ],
      correctAnswer: 1,
      explanation: 'The OpenAI API enables NLP features like chatbots or text generation in backend apps (e.g., Node.js, Flask). It does not generate HTML, schemas, or frontend styles.'
    },
    {
      id: 6,
      question: 'What is a best practice when using AI-generated database queries?',
      options: [
        'Apply queries directly to production databases',
        'Validate queries in a staging environment to avoid data loss',
        'Avoid documenting query logic',
        'Ignore security measures like parameterized queries'
      ],
      correctAnswer: 1,
      explanation: 'Testing AI-generated queries in a staging environment ensures correctness and prevents data issues. Documentation and security (e.g., parameterized queries) are essential, and production deployment without testing is risky.'
    },
    {
      id: 7,
      question: 'In the hands-on project, what is a key requirement for the AI-assisted full-stack app?',
      options: [
        'It must use only vanilla JavaScript',
        'It must include a task manager with a backend, frontend, and chatbot',
        'It must avoid MongoDB for data storage',
        'It must exclude accessibility features'
      ],
      correctAnswer: 1,
      explanation: 'The project requires a task manager app with a Node.js/Express backend, MongoDB, React frontend, and an OpenAI-powered chatbot. It includes accessibility, uses frameworks, and relies on MongoDB.'
    },
    {
      id: 8,
      question: 'What is an ethical consideration when using AI-generated code in the project?',
      options: [
        'Deploying code without testing',
        'Disclosing AI usage in project documentation for transparency',
        'Using Postman to test APIs',
        'Committing code to GitHub'
      ],
      correctAnswer: 1,
      explanation: 'Disclosing AI usage ensures transparency for clients or teams, an ethical necessity. Testing, API validation, and version control are practical steps, not ethical concerns.'
    },
    {
      id: 9,
      question: 'Which tool is recommended for testing the API endpoints of the AI-assisted full-stack app?',
      options: [
        'MongoDB Compass',
        'Postman',
        'Tailwind CSS',
        'Figma AI'
      ],
      correctAnswer: 1,
      explanation: 'Postman is used to test API endpoints (e.g., GET /api/tasks) for functionality and performance. MongoDB Compass manages databases, Tailwind CSS styles frontends, and Figma AI designs layouts.'
    },
    {
      id: 10,
      question: 'What is a recommended resource for learning Node.js and Django for the project?',
      options: [
        'General news websites',
        'MDN Web Docs and Django documentation',
        'Non-technical social media',
        'Local library books'
      ],
      correctAnswer: 1,
      explanation: 'MDN Web Docs and Django\'s official documentation provide accurate, up-to-date resources for Node.js and Django development. General news, non-technical social media, and library books are less relevant or outdated.'
    }
  ]
};
