import type { Lesson } from '@/types/course';

export const lesson5HandsOnProjectAIAssistedStaticWebpage: Lesson = {
  id: 5,
  title: 'Hands-On Project: AI-Assisted Static Webpage',
  duration: '45 minutes',
  type: 'video',
  content: {
    videoUrl: 'https://youtu.be/_GTMOmRrqkU',
    textContent: `<div class="lesson-content">

<h1>Hands-On Project: AI-Assisted Static Webpage</h1>

<div class="intro-section">
<p class="lead-text">Create a responsive portfolio webpage using AI assistance for code generation, styling, and debugging.</p>
</div>

<h2>Project Overview</h2>

<div class="project-overview">
<p>Build a personal portfolio website with the following sections:</p>
<ul>
<li>Header with navigation</li>
<li>Hero section with introduction</li>
<li>About section</li>
<li>Skills section</li>
<li>Contact form</li>
<li>Footer</li>
</ul>
</div>

<h2>Step-by-Step Process</h2>

<div class="steps-section">
<div class="step-item">
<h3>Step 1: Set Up Project Structure</h3>
<p>Create a new folder with index.html, styles.css, and script.js files.</p>
</div>

<div class="step-item">
<h3>Step 2: Generate HTML Structure</h3>
<p>Ask AI: "Create an HTML structure for a portfolio website with header, hero, about, skills, contact, and footer sections."</p>
</div>

<div class="step-item">
<h3>Step 3: Style with CSS</h3>
<p>Ask AI: "Generate responsive CSS for the portfolio with a modern design, using Flexbox and media queries."</p>
</div>

<div class="step-item">
<h3>Step 4: Add Interactivity</h3>
<p>Ask AI: "Create JavaScript for smooth scrolling navigation and form validation."</p>
</div>

<div class="step-item">
<h3>Step 5: Debug and Optimize</h3>
<p>Use AI to identify and fix any issues, then test responsiveness.</p>
</div>
</div>

<h2>AI Prompts to Use</h2>

<div class="prompts-section">
<div class="prompt-item">
<h3>HTML Structure</h3>
<p>"Create a semantic HTML structure for a portfolio website with navigation, hero section, about, skills, contact form, and footer."</p>
</div>

<div class="prompt-item">
<h3>CSS Styling</h3>
<p>"Generate modern CSS for a portfolio website with responsive design, using CSS Grid and Flexbox. Include hover effects and smooth transitions."</p>
</div>

<div class="prompt-item">
<h3>JavaScript Functionality</h3>
<p>"Write JavaScript for smooth scrolling navigation links and form validation for a contact form."</p>
</div>

<div class="prompt-item">
<h3>Responsive Design</h3>
<p>"Add media queries to make the portfolio mobile-friendly with a hamburger menu for navigation."</p>
</div>
</div>

<h2>Testing and Validation</h2>

<div class="testing-section">
<div class="test-item">
<h3>🧪 Browser Testing</h3>
<p>Test the website in different browsers (Chrome, Firefox, Safari) to ensure compatibility.</p>
</div>

<div class="test-item">
<h3>📱 Responsive Testing</h3>
<p>Use browser dev tools to test different screen sizes and ensure the layout adapts properly.</p>
</div>

<div class="test-item">
<h3>♿ Accessibility Testing</h3>
<p>Use tools like Lighthouse to check for accessibility issues and fix them.</p>
</div>

<div class="test-item">
<h3>⚡ Performance Testing</h3>
<p>Optimize images and CSS to improve loading speed.</p>
</div>
</div>

<h2>Best Practices</h2>

<div class="best-practices-section">
<div class="practice-item">
<h3>📝 Document AI Usage</h3>
<p>Keep a log of which AI tools you used and what they helped you create.</p>
</div>

<div class="practice-item">
<h3>🔍 Review Generated Code</h3>
<p>Always review and understand the code generated by AI before using it.</p>
</div>

<div class="practice-item">
<h3>🎨 Customize Design</h3>
<p>Customize the AI-generated design to reflect your personal style and preferences.</p>
</div>

<div class="practice-item">
<h3>💾 Version Control</h3>
<p>Use Git to track changes and save your project to GitHub for portfolio purposes.</p>
</div>
</div>

<div class="highlight-box">
<strong>🎯 Key Takeaway:</strong> This hands-on project demonstrates how AI can accelerate web development while still requiring human creativity and oversight. The combination of AI assistance and manual refinement creates a professional, responsive portfolio website.
</div>

</div>`
  }
};
