import type { Lesson } from '@/types/course';

const lesson: Lesson = {
  id: 2,
  title: 'DC and AC Current in Solar Systems',
  duration: '20 minutes',
  type: 'video',
  videoUrl: 'https://youtu.be/qaNvzoJ5rVI',
  content: `
# DC and AC Current in Solar Systems 🔋

DC (direct current) and AC (alternating current) are fundamental to solar PV operations: panels generate DC for direct use in batteries or conversion, while AC powers standard appliances and grid exports, with inverters bridging the two to minimize 5-10% conversion losses. DC flows unidirectionally for efficient storage, but AC's sinusoidal waveform suits long-distance transmission; mismatches can cause inefficiencies or faults. In 2025, amid a 64% surge in global solar capacity to 380 GW in H1, advanced hybrid inverters with AI controls are enhancing DC-AC integration, boosting efficiencies to 98%+ and supporting 39 GWac U.S. additions per EIA projections.

## Key Concepts

### 1. DC Current in Solar Systems
Generated by PV modules (8-12A per panel at Imp) and stored in batteries; flows steadily from positive to negative, ideal for off-grid loads but prone to voltage drops over distance. High-voltage DC strings (300-1000V) reduce wiring losses in utility-scale arrays.

### 2. AC Current in Solar Systems
Output from inverters (typically 120/240V, 60Hz in U.S.), matching grid standards for seamless export; measured in RMS amps, with three-phase options for commercial setups to handle 50-200A peaks.

### 3. Conversion Process
Inverters use PWM or MPPT to convert DC to AC, incorporating transformers for isolation; hybrids allow bidirectional flow for charging batteries from grid AC, with 2025 models featuring zero-export modes to comply with urban limits.

### 4. Efficiency and Measurement Differences
DC systems face diode and soiling losses (2-5%), while AC encounters harmonic distortions (<5% THD per IEEE 519); tools distinguish via polarity (DC unidirectional) vs. waveform (AC oscillatory).

## Best Practices

### Handling and Sizing Guidelines
Size DC cables for 1.25x Isc ampacity (NEC 690); use sine wave inverters for clean AC to avoid appliance damage, targeting <2% voltage ripple.

### Integration with System Design
Monitor DC currents pre-inverter for MPPT tuning; in hybrids, enable AC-coupled batteries for flexible charging, reducing peak demand by 20-30%.

### Safety and Testing Adjustments
Employ insulated tools for live DC (up to 1500V); test AC waveforms annually to ensure <3% distortion, adapting for 2025 high-frequency exports.

### Common Pitfalls to Avoid
- Confusing DC polarity during wiring (reverse causes fires)
- Undersizing AC breakers for surge currents (2-3x nominal)
- Ignoring ground faults in DC that propagate to AC

### Sustainability Tie-In
Optimize DC retention for direct DC loads (e.g., LEDs) to skip conversion losses, aligning with 2025 IEA-PVPS goals for 20% market growth and lower grid carbon footprints.

---

## Key Takeaways

✅ **DC Generation**: 8-12A per panel at Imp, flows unidirectionally  
✅ **AC Output**: 120/240V @ 60Hz standard in U.S.  
✅ **Conversion Loss**: 5-10% typical in DC-to-AC conversion  
✅ **Efficiency**: 98%+ with advanced hybrid inverters in 2025  
✅ **THD Standard**: <5% harmonic distortion per IEEE 519  
✅ **Peak Reduction**: 20-30% with AC-coupled battery systems  
  `
};

export default lesson;

