// Course ID to title mapping utility
export const getCourseTitle = (courseId: string): string => {
  const courseMap: Record<string, string> = {
    'f9e8d7c6-b5a4-9382-c1d0-e9f8a7b6c5d5': 'Sound Engineering',
    'roofing101': 'Roofing',
    'plumbing101': 'Plumbing',
    'landscaping101': 'Landscaping',
    'podcast-management-101': 'Podcast Management',
    'motor-mechanic-petrol': 'Petrol Motor Mechanic',
    'diesel-mechanic': 'Diesel Motor Mechanic',
    'motor-mechanic-diesel': 'Diesel Motor Mechanic',
    'cellphone-repairs': 'Cellphone Repairs',
    'computer-repairs': 'Computer & Laptop Repairs',
    'ai-human-relations': 'AI and Human Relations',
    'hair-dressing': 'Hair Dressing',
    'nail-technician': 'Nail Technician',
    'entrepreneurship-final': 'Entrepreneurship',
    'tiling-101': 'Tiling 101',
    'motor-mechanic-petrol-02': 'Petrol Motor Mechanic',
    'cellphone-repairs-101': 'Cellphone Repairs',
    'podcast-management': 'Podcast Management',
    'sound-engineering': 'Sound Engineering',
    'business': 'Business',
    'broadcasting': 'Broadcasting',
    'computer-2': 'Computer Repairs',
    'roofing-mastery': 'Roofing Mastery',
    'plumbing-course': 'Plumbing',
    'tiling-course': 'Tiling',
    'hair-dressing-course': 'Hair Dressing',
    'nail-technician-course': 'Nail Technician',
    'cellphone-repairs-course': 'Cellphone Repairs',
    'roofing-course': 'Roofing',
    'motor-mechanic-petrol-course': 'Petrol Motor Mechanic',
    'motor-mechanic-diesel-course': 'Diesel Motor Mechanic',
    'diesel-mechanic-course': 'Diesel Motor Mechanic',
    'computer-repairs-course': 'Computer Repairs',
    'landscaping-course': 'Landscaping',
    'social-media-marketing-101': 'Social Media Marketing 101',
    'social-media-marketing': 'Social Media Marketing 101',
    'electrician101': 'Master Electrician Online',
    'electrician-course': 'Master Electrician Online',
    'solar101': 'Solar Energy Systems: Installation & Maintenance',
    'solar-energy-systems': 'Solar Energy Systems: Installation & Maintenance',
    'solar-course': 'Solar Energy Systems: Installation & Maintenance',
    'carpentry101': 'Carpentry',
    'carpentry-course': 'Carpentry',
    'carpentry': 'Carpentry'
  };
  
  return courseMap[courseId] || 'Unknown Course';
};
