import type { Lesson } from '../../../types/course';

const lesson5Quiz: Lesson = {
  id: 5,
  title: 'Module 5 Quiz: Electrical and Diagnostic Systems',
  duration: '25 minutes',
  type: 'quiz',
  content: {
    questions: [
      {
        question: 'What is the primary function of the Mass Air Flow (MAF) sensor in a diesel engine?',
        options: [
          'To measure exhaust gas temperature',
          'To measure the amount of air entering the engine',
          'To control fuel injection timing',
          'To monitor engine oil pressure'
        ],
        correct: 1,
        explanation: 'The MAF sensor measures the amount of air entering the engine, providing critical data to the ECU for calculating the correct fuel injection amount for optimal combustion.'
      },
      {
        question: 'What does an Engine Control Unit (ECU) do in a modern diesel engine?',
        options: [
          'Only controls the radio system',
          'Manages engine functions like fuel injection, timing, and emissions systems',
          'Controls only the air conditioning',
          'Operates the vehicle\'s lights'
        ],
        correct: 1,
        explanation: 'The ECU is the brain of the engine, managing critical functions including fuel injection timing and quantity, turbocharger control, emissions systems, and overall engine performance optimization.'
      },
      {
        question: 'What is a DTC (Diagnostic Trouble Code)?',
        options: [
          'A type of diesel fuel additive',
          'A standardized code that indicates specific system malfunctions',
          'A maintenance schedule reminder',
          'A fuel efficiency measurement'
        ],
        correct: 1,
        explanation: 'A DTC is a standardized alphanumeric code generated by the vehicle\'s diagnostic systems to indicate specific malfunctions or issues with various engine and vehicle systems.'
      },
      {
        question: 'Which diagnostic tool is most commonly used for reading DTCs in modern diesel vehicles?',
        options: [
          'Basic multimeter only',
          'OBD-II scanner',
          'Simple test light',
          'Mechanical gauge set'
        ],
        correct: 1,
        explanation: 'An OBD-II scanner is the primary diagnostic tool for reading DTCs, monitoring live data, and performing various diagnostic functions on modern diesel vehicles equipped with OBD-II systems.'
      },
      {
        question: 'What is the CAN bus system in a diesel vehicle?',
        options: [
          'A type of fuel injection system',
          'A communication network that allows ECUs to share information',
          'An exhaust aftertreatment system',
          'A manual transmission component'
        ],
        correct: 1,
        explanation: 'The CAN (Controller Area Network) bus is a digital communication system that allows various ECUs throughout the vehicle to share information and coordinate their functions efficiently.'
      },
      {
        question: 'What should you check first when diagnosing electrical problems in a diesel engine?',
        options: [
          'Engine compression',
          'Battery voltage and connections',
          'Fuel quality',
          'Tire pressure'
        ],
        correct: 1,
        explanation: 'Battery voltage and connections should be checked first, as many electrical issues stem from inadequate power supply. Low voltage can cause multiple system malfunctions and false DTCs.'
      },
      {
        question: 'What is the purpose of a coolant temperature sensor?',
        options: [
          'To turn on the radio when the engine warms up',
          'To provide engine temperature data to the ECU for fuel and timing adjustments',
          'To control the vehicle\'s air conditioning',
          'To measure fuel tank temperature'
        ],
        correct: 1,
        explanation: 'The coolant temperature sensor provides critical engine temperature data to the ECU, which uses this information to adjust fuel injection, ignition timing, and other parameters for optimal performance.'
      },
      {
        question: 'What can cause multiple unrelated DTCs to appear simultaneously?',
        options: [
          'Perfect engine condition',
          'Low battery voltage or poor electrical connections',
          'High-quality diesel fuel',
          'Recent oil change'
        ],
        correct: 1,
        explanation: 'Low battery voltage or poor electrical connections can cause multiple unrelated DTCs because various systems may malfunction or report false errors when they don\'t receive adequate electrical power.'
      },
      {
        question: 'What is the first step in proper electrical diagnostic procedure?',
        options: [
          'Replace all sensors immediately',
          'Verify the complaint and gather information about the problem',
          'Start replacing ECUs randomly',
          'Ignore any warning lights'
        ],
        correct: 1,
        explanation: 'The first step is always to verify the complaint and gather detailed information about when and how the problem occurs, driving conditions, and any related symptoms before beginning diagnosis.'
      },
      {
        question: 'Why is it important to clear DTCs and test drive after repairs?',
        options: [
          'To confuse the diagnostic system',
          'To verify that the repair was successful and no new problems exist',
          'DTCs should never be cleared',
          'To make the engine run louder'
        ],
        correct: 1,
        explanation: 'Clearing DTCs and test driving after repairs verifies that the repair was successful, ensures no new problems have been introduced, and confirms that the diagnostic system is functioning properly.'
      }
    ]
  }
};

export default lesson5Quiz;
