import type { Course } from '@/types/course';

export const dieselMechanicCourse: Course = {
  id: 'b8c7d6e5-f4a3-9281-b0c9-d8e7f6a5b4c3',
  title: 'Diesel Mechanic Professional Certification',
  description: 'Master diesel engine diagnostics, repair, and maintenance with hands-on training for heavy-duty vehicles, trucks, and equipment.',
  instructor: {
    name: 'Master Technician Mike Johnson',
    title: 'Certified Diesel Engine Specialist',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
    bio: 'Over 20 years of experience in diesel engine repair and maintenance. Certified by major diesel manufacturers including Caterpillar, Cummins, and Detroit Diesel.'
  },
  level: 'intermediate',
  duration: '16 weeks',
  students: 1247,
  rating: 4.8,
  price: 500,
  currency: 'ZAR',
  is_free: false,
  thumbnail: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
  category: 'Automotive',
  learningObjectives: [
    'Understand diesel engine principles and operation',
    'Diagnose common diesel engine problems',
    'Master fuel injection system repair',
    'Perform preventive maintenance procedures',
    'Use diagnostic tools and equipment effectively',
    'Understand emissions systems and regulations',
    'Repair turbochargers and intercoolers',
    'Troubleshoot electrical systems in diesel vehicles'
  ],
  modules: [
    {
      id: 1,
      title: 'Diesel Engine Fundamentals',
      description: 'Introduction to diesel engine principles, components, and operation',
      lessons: [
        {
          id: 1,
          title: 'Introduction to Diesel Engines',
          duration: '45 min',
          type: 'video',
          content: {
            videoUrl: 'https://www.youtube.com/embed/Q3AqwaRaF0s',
            textContent: `
              <div class="space-y-8">
                <div class="bg-white p-6 rounded-lg shadow-md">
                  <h2 class="text-3xl font-bold text-blue-600 mb-6">Module 1: Diesel Engine Fundamentals</h2>
                  
                  <div class="bg-blue-50 p-4 rounded-lg mb-6">
                    <h3 class="text-xl font-semibold text-blue-800 mb-3">🚛 What is a Diesel Engine?</h3>
                    <p class="text-blue-700 mb-3">
                      A diesel engine is an internal combustion engine that uses compression ignition to burn diesel fuel. Unlike gasoline engines that use spark plugs, diesel engines rely on the heat generated by compressing air to ignite the fuel.
                    </p>
                  </div>

                  <div class="grid md:grid-cols-2 gap-6 mb-6">
                    <div class="bg-green-50 p-4 rounded-lg">
                      <h4 class="text-lg font-semibold text-green-800 mb-3">⚙️ How Diesel Engines Work</h4>
                      <ol class="text-sm text-green-600 list-decimal list-inside space-y-1">
                        <li><strong>Intake:</strong> Air is drawn into the cylinder</li>
                        <li><strong>Compression:</strong> Air is compressed to 1/14-1/25 of original volume</li>
                        <li><strong>Injection:</strong> Diesel fuel is injected at high pressure</li>
                        <li><strong>Combustion:</strong> Fuel ignites from compressed air heat</li>
                        <li><strong>Exhaust:</strong> Burnt gases are expelled</li>
                      </ol>
                    </div>

                    <div class="bg-orange-50 p-4 rounded-lg">
                      <h4 class="text-lg font-semibold text-orange-800 mb-3">🔥 Compression Ignition</h4>
                      <ul class="text-sm text-orange-600 space-y-1">
                        <li>• Compression ratio: 14:1 to 25:1</li>
                        <li>• Temperature reaches 500-700°C</li>
                        <li>• No spark plugs needed</li>
                        <li>• More efficient than gasoline engines</li>
                        <li>• Higher torque at lower RPMs</li>
                      </ul>
                    </div>
                  </div>

                  <div class="bg-purple-50 p-4 rounded-lg mb-6">
                    <h3 class="text-xl font-semibold text-purple-800 mb-3">🔧 Main Components</h3>
                    <div class="grid md:grid-cols-3 gap-4">
                      <div class="border rounded-lg p-3">
                        <h4 class="font-semibold text-purple-700 mb-2">Engine Block</h4>
                        <p class="text-sm text-gray-700">Houses cylinders, crankshaft, and cooling passages</p>
                      </div>
                      <div class="border rounded-lg p-3">
                        <h4 class="font-semibold text-purple-700 mb-2">Cylinder Head</h4>
                        <p class="text-sm text-gray-700">Contains valves, injectors, and combustion chambers</p>
                      </div>
                      <div class="border rounded-lg p-3">
                        <h4 class="font-semibold text-purple-700 mb-2">Fuel System</h4>
                        <p class="text-sm text-gray-700">Delivers fuel at precise timing and pressure</p>
                      </div>
                    </div>
                  </div>

                  <div class="bg-yellow-50 p-4 rounded-lg mb-6">
                    <h3 class="text-xl font-semibold text-yellow-800 mb-3">📊 Diesel vs Gasoline Engines</h3>
                    <div class="overflow-x-auto">
                      <table class="w-full text-sm">
                        <thead>
                          <tr class="border-b">
                            <th class="text-left p-2">Aspect</th>
                            <th class="text-left p-2">Diesel</th>
                            <th class="text-left p-2">Gasoline</th>
                          </tr>
                        </thead>
                        <tbody class="text-gray-600">
                          <tr class="border-b">
                            <td class="p-2 font-medium">Ignition</td>
                            <td class="p-2">Compression</td>
                            <td class="p-2">Spark plug</td>
                          </tr>
                          <tr class="border-b">
                            <td class="p-2 font-medium">Compression Ratio</td>
                            <td class="p-2">14:1 to 25:1</td>
                            <td class="p-2">8:1 to 12:1</td>
                          </tr>
                          <tr class="border-b">
                            <td class="p-2 font-medium">Fuel Efficiency</td>
                            <td class="p-2">Higher (25-40% better)</td>
                            <td class="p-2">Lower</td>
                          </tr>
                          <tr class="border-b">
                            <td class="p-2 font-medium">Torque</td>
                            <td class="p-2">Higher at low RPM</td>
                            <td class="p-2">Higher at high RPM</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>

                  <div class="bg-red-50 p-4 rounded-lg">
                    <h3 class="text-xl font-semibold text-red-800 mb-3">🚨 Safety Considerations</h3>
                    <ul class="text-red-700 space-y-2">
                      <li>• High-pressure fuel systems (up to 30,000 PSI)</li>
                      <li>• Hot exhaust gases and components</li>
                      <li>• Heavy components requiring proper lifting techniques</li>
                      <li>• Toxic exhaust emissions - ensure proper ventilation</li>
                      <li>• Use proper PPE including safety glasses and gloves</li>
                    </ul>
                  </div>
                </div>
              </div>
            `
          }
        },
        {
          id: 2,
          title: 'Module 1 Quiz: Diesel Engine Fundamentals',
          duration: '15 min',
          type: 'quiz',
          content: {
            questions: [
              {
                question: 'How do diesel engines ignite fuel?',
                options: [
                  'Using spark plugs',
                  'Through compression ignition',
                  'With glow plugs only',
                  'Using electrical arcs'
                ],
                correct: 1,
                explanation: 'Diesel engines use compression ignition - the heat generated by compressing air ignites the diesel fuel.'
              },
              {
                question: 'What is the typical compression ratio range for diesel engines?',
                options: [
                  '8:1 to 12:1',
                  '10:1 to 14:1',
                  '14:1 to 25:1',
                  '25:1 to 30:1'
                ],
                correct: 2,
                explanation: 'Diesel engines typically have compression ratios between 14:1 and 25:1, much higher than gasoline engines.'
              },
              {
                question: 'What is a major advantage of diesel engines over gasoline engines?',
                options: [
                  'Lower initial cost',
                  'Quieter operation',
                  'Better fuel efficiency',
                  'Faster acceleration'
                ],
                correct: 2,
                explanation: 'Diesel engines are typically 25-40% more fuel efficient than gasoline engines due to higher energy density of diesel fuel and higher compression ratios.'
              }
            ]
          }
        }
      ]
    },
    {
      id: 2,
      title: 'Fuel Injection Systems',
      description: 'Understanding and servicing diesel fuel injection systems',
      lessons: [
        {
          id: 3,
          title: 'Common Rail Fuel Systems',
          duration: '60 min',
          type: 'video',
          content: {
            videoUrl: 'https://www.youtube.com/embed/ZloaiB7VPgE',
            textContent: `
              <div class="space-y-8">
                <div class="bg-white p-6 rounded-lg shadow-md">
                  <h2 class="text-3xl font-bold text-blue-600 mb-6">Common Rail Fuel Injection Systems</h2>
                  
                  <div class="bg-blue-50 p-4 rounded-lg mb-6">
                    <h3 class="text-xl font-semibold text-blue-800 mb-3">🔧 What is Common Rail?</h3>
                    <p class="text-blue-700 mb-3">
                      Common Rail is a modern fuel injection system where fuel is stored in a high-pressure rail and distributed to individual injectors. This allows for precise control of injection timing, pressure, and quantity.
                    </p>
                  </div>

                  <div class="grid md:grid-cols-2 gap-6 mb-6">
                    <div class="bg-green-50 p-4 rounded-lg">
                      <h4 class="text-lg font-semibold text-green-800 mb-3">⚙️ System Components</h4>
                      <ul class="text-sm text-green-600 space-y-1">
                        <li>• High-pressure fuel pump</li>
                        <li>• Common rail (fuel accumulator)</li>
                        <li>• Electronic injectors</li>
                        <li>• Pressure sensors</li>
                        <li>• Engine Control Unit (ECU)</li>
                        <li>• Fuel filter and cooler</li>
                      </ul>
                    </div>

                    <div class="bg-orange-50 p-4 rounded-lg">
                      <h4 class="text-lg font-semibold text-orange-800 mb-3">📊 Operating Pressures</h4>
                      <ul class="text-sm text-orange-600 space-y-1">
                        <li>• Low pressure: 5-10 bar</li>
                        <li>• High pressure: 300-2500+ bar</li>
                        <li>• Latest systems: up to 3000 bar</li>
                        <li>• Pressure varies with load/speed</li>
                        <li>• ECU controls via pressure regulator</li>
                      </ul>
                    </div>
                  </div>

                  <div class="bg-yellow-50 p-4 rounded-lg mb-6">
                    <h3 class="text-xl font-semibold text-yellow-800 mb-3">🔍 Advantages of Common Rail</h3>
                    <div class="grid md:grid-cols-2 gap-4">
                      <div>
                        <h4 class="font-semibold text-yellow-700 mb-2">Performance Benefits:</h4>
                        <ul class="text-sm text-gray-600 space-y-1">
                          <li>• Multiple injections per cycle</li>
                          <li>• Precise fuel metering</li>
                          <li>• Improved combustion efficiency</li>
                          <li>• Better power and torque</li>
                        </ul>
                      </div>
                      <div>
                        <h4 class="font-semibold text-yellow-700 mb-2">Environmental Benefits:</h4>
                        <ul class="text-sm text-gray-600 space-y-1">
                          <li>• Reduced emissions</li>
                          <li>• Lower noise levels</li>
                          <li>• Better fuel economy</li>
                          <li>• Cleaner combustion</li>
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div class="bg-red-100 p-4 rounded-lg">
                    <h3 class="text-xl font-semibold text-red-800 mb-3">⚠️ Safety Warning</h3>
                    <p class="text-red-700">
                      <strong>EXTREME HIGH PRESSURE:</strong> Common rail systems operate at pressures up to 3000 bar (43,500 PSI). 
                      Never attempt to service pressurized components. Always depressurize system before maintenance.
                    </p>
                  </div>
                </div>
              </div>
            `
          }
        }
      ]
    },
    {
      id: 3,
      title: 'Engine Diagnostics',
      description: 'Diagnostic procedures and troubleshooting techniques',
      lessons: [
        {
          id: 4,
          title: 'Using Diagnostic Scanners',
          duration: '50 min',
          type: 'video',
          content: {
            videoUrl: 'https://www.youtube.com/embed/Yh8-0bj3_sI',
            textContent: `
              <div class="space-y-8">
                <div class="bg-white p-6 rounded-lg shadow-md">
                  <h2 class="text-3xl font-bold text-blue-600 mb-6">Diesel Engine Diagnostics</h2>
                  
                  <div class="bg-blue-50 p-4 rounded-lg mb-6">
                    <h3 class="text-xl font-semibold text-blue-800 mb-3">🔍 Modern Diagnostic Approach</h3>
                    <p class="text-blue-700 mb-3">
                      Modern diesel engines are equipped with sophisticated electronic systems that monitor performance and detect faults. Proper diagnostic procedures are essential for efficient troubleshooting.
                    </p>
                  </div>

                  <div class="grid md:grid-cols-2 gap-6 mb-6">
                    <div class="bg-green-50 p-4 rounded-lg">
                      <h4 class="text-lg font-semibold text-green-800 mb-3">🛠️ Diagnostic Tools</h4>
                      <ul class="text-sm text-green-600 space-y-1">
                        <li>• OBD-II scanners</li>
                        <li>• Manufacturer-specific tools</li>
                        <li>• Oscilloscopes</li>
                        <li>• Pressure gauges</li>
                        <li>• Flow meters</li>
                        <li>• Temperature sensors</li>
                      </ul>
                    </div>

                    <div class="bg-orange-50 p-4 rounded-lg">
                      <h4 class="text-lg font-semibold text-orange-800 mb-3">📋 Diagnostic Process</h4>
                      <ol class="text-sm text-orange-600 list-decimal list-inside space-y-1">
                        <li>Visual inspection</li>
                        <li>Read fault codes</li>
                        <li>Check live data</li>
                        <li>Perform function tests</li>
                        <li>Component testing</li>
                        <li>Verify repair</li>
                      </ol>
                    </div>
                  </div>

                  <div class="bg-purple-50 p-4 rounded-lg mb-6">
                    <h3 class="text-xl font-semibold text-purple-800 mb-3">⚡ Common Fault Codes</h3>
                    <div class="overflow-x-auto">
                      <table class="w-full text-sm">
                        <thead>
                          <tr class="border-b">
                            <th class="text-left p-2">Code</th>
                            <th class="text-left p-2">Description</th>
                            <th class="text-left p-2">Common Cause</th>
                          </tr>
                        </thead>
                        <tbody class="text-gray-600">
                          <tr class="border-b">
                            <td class="p-2 font-medium">P0087</td>
                            <td class="p-2">Fuel rail pressure too low</td>
                            <td class="p-2">Fuel pump, filter, or leak</td>
                          </tr>
                          <tr class="border-b">
                            <td class="p-2 font-medium">P0088</td>
                            <td class="p-2">Fuel rail pressure too high</td>
                            <td class="p-2">Pressure regulator fault</td>
                          </tr>
                          <tr class="border-b">
                            <td class="p-2 font-medium">P0201-P0208</td>
                            <td class="p-2">Injector circuit fault</td>
                            <td class="p-2">Faulty injector or wiring</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              </div>
            `
          }
        }
      ]
    },
    {
      id: 4,
      title: 'Preventive Maintenance',
      description: 'Scheduled maintenance procedures and best practices',
      lessons: [
        {
          id: 5,
          title: 'Oil and Filter Services',
          duration: '40 min',
          type: 'video',
          content: {
            videoUrl: 'https://www.youtube.com/embed/MEoRP2gOFWQ',
            textContent: `
              <div class="space-y-8">
                <div class="bg-white p-6 rounded-lg shadow-md">
                  <h2 class="text-3xl font-bold text-blue-600 mb-6">Diesel Engine Maintenance</h2>
                  
                  <div class="bg-blue-50 p-4 rounded-lg mb-6">
                    <h3 class="text-xl font-semibold text-blue-800 mb-3">🛠️ Preventive Maintenance Importance</h3>
                    <p class="text-blue-700 mb-3">
                      Regular maintenance is crucial for diesel engines due to their high operating pressures, temperatures, and the demanding environments they typically operate in.
                    </p>
                  </div>

                  <div class="grid md:grid-cols-2 gap-6 mb-6">
                    <div class="bg-green-50 p-4 rounded-lg">
                      <h4 class="text-lg font-semibold text-green-800 mb-3">🔧 Key Maintenance Tasks</h4>
                      <ul class="text-sm text-green-600 space-y-1">
                        <li>• Oil and filter changes</li>
                        <li>• Fuel filter replacement</li>
                        <li>• Air filter maintenance</li>
                        <li>• Coolant system service</li>
                        <li>• Belt and hose inspection</li>
                        <li>• Turbocharger maintenance</li>
                      </ul>
                    </div>

                    <div class="bg-orange-50 p-4 rounded-lg">
                      <h4 class="text-lg font-semibold text-orange-800 mb-3">📅 Service Intervals</h4>
                      <ul class="text-sm text-orange-600 space-y-1">
                        <li>• Oil change: 5,000-15,000 miles</li>
                        <li>• Fuel filter: 10,000-20,000 miles</li>
                        <li>• Air filter: 15,000-30,000 miles</li>
                        <li>• Coolant: 100,000-150,000 miles</li>
                        <li>• Timing belt: 60,000-100,000 miles</li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            `
          }
        }
      ]
    },
    {
      id: 5,
      title: 'Final Assessment',
      description: 'Comprehensive assessment of diesel mechanic skills',
      lessons: [
        {
          id: 6,
          title: 'Diesel Mechanic Certification Exam',
          duration: '90 min',
          type: 'quiz',
          content: {
            questions: [
              {
                question: 'What is the primary difference between diesel and gasoline engines?',
                options: [
                  'Diesel engines use spark plugs',
                  'Diesel engines use compression ignition',
                  'Diesel engines run at higher RPMs',
                  'Diesel engines use carburetors'
                ],
                correct: 1,
                explanation: 'Diesel engines use compression ignition instead of spark plugs to ignite the fuel.'
              },
              {
                question: 'What pressure range do modern common rail systems operate at?',
                options: [
                  '50-100 bar',
                  '100-300 bar',
                  '300-3000+ bar',
                  '3000-5000 bar'
                ],
                correct: 2,
                explanation: 'Modern common rail systems typically operate between 300-3000+ bar pressure.'
              },
              {
                question: 'Which diagnostic code typically indicates low fuel rail pressure?',
                options: [
                  'P0087',
                  'P0088',
                  'P0201',
                  'P0300'
                ],
                correct: 0,
                explanation: 'P0087 indicates fuel rail pressure too low, often caused by fuel pump, filter, or leak issues.'
              },
              {
                question: 'How often should diesel engine oil typically be changed in heavy-duty applications?',
                options: [
                  '3,000-5,000 miles',
                  '5,000-15,000 miles',
                  '15,000-25,000 miles',
                  '25,000-50,000 miles'
                ],
                correct: 1,
                explanation: 'Diesel engine oil change intervals typically range from 5,000-15,000 miles depending on operating conditions.'
              },
              {
                question: 'What is the main safety concern when working on common rail fuel systems?',
                options: [
                  'Electrical shock',
                  'Extreme high pressure',
                  'Hot surfaces',
                  'Toxic fumes'
                ],
                correct: 1,
                explanation: 'Common rail systems operate at extremely high pressures (up to 3000 bar) which can cause serious injury.'
              }
            ]
          }
        },
        {
          id: 7,
          title: 'Course Completion Certificate',
          duration: '5 min',
          type: 'certificate',
          content: {
            title: 'Diesel Mechanic Professional Certification',
            description: 'Congratulations on completing the comprehensive Diesel Mechanic course!',
            certificateText: 'This certifies that the holder has successfully completed the Diesel Mechanic Professional Certification course and has demonstrated proficiency in diesel engine diagnostics, repair, and maintenance.'
          }
        }
      ]
    }
  ]
};
